/*
This file contains the icons that are used in the application.  When additional icons are required,
they should be imported in this file and added to the `IconRegistry` array.
*/
import {
  faCircleQuestion,
  faFileImage,
  faFileVideo,
  faFileAudio,
  faFileArchive,
  faFilePdf,
  faFilePowerpoint,
  faFileExcel,
  faFileWord,
  faFile,
} from "@fortawesome/free-regular-svg-icons";
import {
  faArrowDown,
  faArrowUp,
  faDatabase,
  faTriangleExclamation,
  faCircleCheck,
  faCircleExclamation,
  faXmark,
  faUserCircle,
  faChevronDown,
  faFileCsv,
  faBank,
  faFileImport,
  faCircleNotch,
  faServer,
  faCaretDown,
  faCaretUp,
  faTimesCircle,
} from "@fortawesome/free-solid-svg-icons";

export const FREE_ICON_REGISTRY = [
  faArrowDown,
  faArrowUp,
  faDatabase,
  faTriangleExclamation,
  faCircleCheck,
  faCircleExclamation,
  faXmark,
  faUserCircle,
  faChevronDown,
  faCircleQuestion,
  faFileImage,
  faFileVideo,
  faFileAudio,
  faFileArchive,
  faFilePdf,
  faFilePowerpoint,
  faFileExcel,
  faFileWord,
  faFileCsv,
  faFile,
  faBank,
  faFileImport,
  faCircleNotch,
  faServer,
  faCaretDown,
  faCaretUp,
  faTimesCircle,
] as const;
