/*
This file contains the icons that are used in the application when the FontAwesome license is in
use.  When additional icons are required, they should be imported in this file and added to the
`IconRegistry` array.
*/
import {
  faCircleQuestion,
  faFileImage,
  faFileVideo,
  faFileAudio,
  faFileArchive,
  faFilePdf,
  faFilePowerpoint,
  faFileExcel,
  faFileWord,
  faFile,
  faTrashAlt,
} from "@fortawesome/pro-regular-svg-icons";
import {
  faArrowDown,
  faArrowUp,
  faDatabase,
  faTriangleExclamation,
  faCircleCheck,
  faCircleExclamation,
  faXmark,
  faUserCircle,
  faChevronDown,
  faFileCsv,
  faBank,
  faFileImport,
  faCircleNotch,
  faServer,
  faCaretDown,
  faCaretUp,
  faTimesCircle,
  faPlusCircle,
  faFilter,
  faSortAmountDown,
} from "@fortawesome/pro-solid-svg-icons";

export const PRO_ICON_REGISTRY = [
  faArrowDown,
  faArrowUp,
  faDatabase,
  faTriangleExclamation,
  faCircleCheck,
  faCircleExclamation,
  faXmark,
  faUserCircle,
  faChevronDown,
  faCircleQuestion,
  faFileImage,
  faFileVideo,
  faFileAudio,
  faFileArchive,
  faFilePdf,
  faFilePowerpoint,
  faFileExcel,
  faFileWord,
  faFileCsv,
  faFile,
  faBank,
  faFileImport,
  faCircleNotch,
  faServer,
  faCaretDown,
  faCaretUp,
  faTimesCircle,
  faPlusCircle,
  faTrashAlt,
  faFilter,
  faSortAmountDown,
] as const;
